### ISSUE TITLE
Ability to mark exception messages as safe

### ISSUE THREAD

**Issue by ash211** [palantir/safe-logging#11]
For debuggability I need the ability to mark exception messages as safe or unsafe (right now they're all unsafe by default) so they can be picked up and used by various tools.

As an example of where this would be useful, the contents of [this message in http-remoting](https://github.com/palantir/http-remoting/blob/2.6.1/error-handling/src/main/java/com/palantir/remoting2/errors/SerializableErrorToExceptionConverter.java#L51) will always be safe (e.g. `500 Internal Server Error`), so I'd like to mark it as safe in some way so it can be logged appropriately.

One possible implementation is `SafeRuntimeException`, `SafeIllegalArgumentException`, etc classes

**Comment by uschi2000** [comment]
see here: https://github.com/palantir/http-remoting/pull/417

**Comment by gracew** [comment]
Even with https://github.com/palantir/http-remoting-api/pull/9 I think we'll need some basic preconditions-type functionality for libraries, which won't be throwing `ServiceException`s.

**Comment by dekramer** [comment]
+1, at present it's basically not possible to do anything useful with stack traces in Aries without either reading the source code or sshing onto the box with the logs because the exception messages are missing from the stack traces.

**Comment by ash211** [comment]
This is preventing me from using collected sls logs to debug an issue I'm working right now, so I have to access logs directly on the box since a stacktrace message is missing

**Comment by markelliot** [comment]
As Rob links above, we're adding support for this in http-remoting3.

**Comment by ash211** [comment]
That's not enough since we need the ability to mark exception messages from non-Palantir libraries as safe also, not just exceptions from http-remoting

**Comment by markelliot** [comment]
Then you should catch and rethrow those exceptions as needed.

**Comment by gracew** [comment]
closed in #28
