### ISSUE TITLE
New SafeLogger.forEnclosingClass() 

### ISSUE THREAD

**Issue by ash211** [palantir/safe-logging#772]
## What happened?

Currently, classes access a SafeLogger like this:

```
public final class MyClass {
    private static final SafeLogger log = SafeLoggerFactory.get(MyClass.class);
   ...
}
```

This makes it possible to pass a different parameter to the factory's get method than the class it's in, like this antipattern:

```
public final class MyClass {
    private static final SafeLogger log = SafeLoggerFactory.get(OtherClass.class);  // <-- OtherClass ???
   ...
}
```

## What did you want to happen?

Instead, we could use a pattern that removes the need for this parameter entirely:

```
public final class MyClass {
    private static final SafeLogger log = SafeLogger.forEnclosingClass();
   ...
}
```

This is inspired by `GoogleLogger.forEnclosingClass()` [here](https://github.com/google/flogger/blob/d2f442dbd373b1d883f3ca6b65229221d0a7e914/google/src/main/java/com/google/common/flogger/GoogleLogger.java#L44-L50), which is widely used by Google.

Using the `forEnclosingClass()` pattern instead of taking the parameter will make the SafeLogger API less error-prone and harder to use incorrectly.

**Comment by carterkozak** [comment]
The trade-off is that such discovery is relatively expensive, and must be done at runtime each time the application is started for each logger. We prevent the `SafeLoggerFactory.get(OtherClass.class)` failure using static-analysis, which isn't as nice an API as automatic detection, however we pay the cost in the right place (compile time).
See [LoggerEnclosingClass](https://github.com/palantir/gradle-baseline/blob/20c2a697f8f54c28ce1cd2fa77615e930d0570e0/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java) and [related tests](https://github.com/palantir/gradle-baseline/blob/779c6db14689b312bbdb2f4bc705cdfe2f61f078/baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LoggerEnclosingClassTest.java).

**Comment by ash211** [comment]
Thanks for sharing those links!  I wonder why flogger chose to make that tradeoff.  Maybe they've somehow hacked the JVM to make that reflection cheaper?

Anyways, this would just be a slightly nicer ergonomics so probably not worth it for us.
